#!/bin/bash

BASED=`dirname $0`

# set DEV to whatever your wifi device is
DEV=wlan0
DEV=wlo1

cd $BASED

date

nmcli connection show --active | grep wifi
if [ $? = 0 ]
then
  exit 0
fi

LIST=`nmcli device wifi list | tr -s ' ' | cut -f 2 -d ' '  | grep -v -- -- | grep -v SSID | sort | uniq`

for n in $LIST
do
  if [ -f $n ]
  then
    echo found $n, bringing it up

    ID=`nmcli connection | grep $n | tr -s ' ' | cut -f 2 -d ' ' | head -n 1`
    echo $ID
    nmcli connection modify uuid $ID ipv4.route-metric 100
    nmcli connection modify uuid $ID ipv6.route-metric 100

    nmcli connection up ifname $DEV ap $n passwd-file $n
    exit 0
  fi
done
